INSERT INTO Settings(ip_address, port) VALUES('192.168.100.1', '8080');

INSERT INTO Pictogram(name, category_id)VALUES('no', null);
INSERT INTO Pictogram(name, category_id)VALUES('si', null);
INSERT INTO Pictogram(name, category_id)VALUES('banio', 2);
INSERT INTO Pictogram(name, category_id)VALUES('sed_ninia',2);
INSERT INTO Pictogram(name, category_id)VALUES('sed_ninio',2);
INSERT INTO Pictogram(name, category_id)VALUES('cansada',2);
INSERT INTO Pictogram(name, category_id)VALUES('cansado',2);
INSERT INTO Pictogram(name, category_id)VALUES('dolorida',3);
INSERT INTO Pictogram(name, category_id)VALUES('dolorido',3);
INSERT INTO Pictogram(name, category_id)VALUES('triste_ninia',3);
INSERT INTO Pictogram(name, category_id)VALUES('triste_ninio',3);
INSERT INTO Pictogram(name, category_id)VALUES('sorprendida',3);
INSERT INTO Pictogram(name, category_id)VALUES('sorprendido',3);
INSERT INTO Pictogram(name, category_id)VALUES('asustada',3);
INSERT INTO Pictogram(name, category_id)VALUES('asustado',3);
INSERT INTO Pictogram(name, category_id)VALUES('contenta',3);
INSERT INTO Pictogram(name, category_id)VALUES('contento',3);
INSERT INTO Pictogram(name, category_id)VALUES('enojada',3);
INSERT INTO Pictogram(name, category_id)VALUES('enojado',3);
INSERT INTO Pictogram(name, category_id)VALUES('caballo',1);
INSERT INTO Pictogram(name, category_id)VALUES('casco',1);
INSERT INTO Pictogram(name, category_id)VALUES('cepillo',1);
INSERT INTO Pictogram(name, category_id)VALUES('zanahoria',1);
INSERT INTO Pictogram(name, category_id)VALUES('limpieza',1);
INSERT INTO Pictogram(name, category_id)VALUES('escarba_vasos',1);
INSERT INTO Pictogram(name, category_id)VALUES('montura',1);
INSERT INTO Pictogram(name, category_id)VALUES('matra',1);
INSERT INTO Pictogram(name, category_id)VALUES('pasto',1);
INSERT INTO Pictogram(name, category_id)VALUES('riendas',1);
INSERT INTO Pictogram(name, category_id)VALUES('rasqueta_dura',1);
INSERT INTO Pictogram(name, category_id)VALUES('rasqueta_blanda',1);
INSERT INTO Pictogram(name, category_id)VALUES('caballo',0);
INSERT INTO Pictogram(name, category_id)VALUES('caballo',0);
INSERT INTO Pictogram(name, category_id)VALUES('chapas',0);
INSERT INTO Pictogram(name, category_id)VALUES('burbujas',0);
INSERT INTO Pictogram(name, category_id)VALUES('broches',0);
INSERT INTO Pictogram(name, category_id)VALUES('aro',0);
INSERT INTO Pictogram(name, category_id)VALUES('letras',0);
INSERT INTO Pictogram(name, category_id)VALUES('maracas',0);
INSERT INTO Pictogram(name, category_id)VALUES('palos',0);
INSERT INTO Pictogram(name, category_id)VALUES('cubos',0);
INSERT INTO Pictogram(name, category_id)VALUES('pato',0);
INSERT INTO Pictogram(name, category_id)VALUES('pelota',0);